services:
  redis:
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    image: redis:7-alpine
    container_name: cvelixir_redis
    restart: unless-stopped

  cvelixir:
    build: .
    container_name: cvelixir_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs