services:
  redis:
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    image: redis:7-alpine
    container_name: cvelixir_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    container_name: cvelixir_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cvelixir:
    build: .
    container_name: cvelixir_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs

  web:  # <-- НОВЫЙ СЕРВИС
    build: .
    container_name: cvelixir_web
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    depends_on:
      - postgres
      - redis
    command: uvicorn app.web:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./logs:/app/logs

volumes:
  redis_data:
  postgres_data: