KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret"
    user_cvelixir="cvelixir-secret";
};

Client {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="cvelixir"
    password="cvelixir-secret";
};